[build]
  publish = "public"
  functions = "netlify/functions"

# Netlify already handles function proxying automatically
# No need for custom redirects for functions

[build.environment]
  NODE_VERSION = "16" 